[package]
authors = ["Pooya Eimandar <pooya.eimandar@live.com>"]
edition = "2018"
name = "VulkanRust"
version = "0.1.0"

[dependencies]
ash = {version = "0.33"}
ash-window = {version = "0.7"}
futures = {version = "0.3"}
mimalloc = {version = "0.1"}
winit = {version = "0.25"}
